version: "3.8"
networks:
  app_network:
    external: true
services:
  server:
    container_name: multicontainer_todo_srv-${NODE_ENV}
    build:
      context: ../../srv
      args:
        NODE_ENV: ${NODE_ENV}
      dockerfile: Dockerfile
    env_file:
      - ../../srv/.env.${NODE_ENV}
      - ../../srv/src/db/.env.${NODE_ENV}
    ports:
      - '${BACKEND_PORT_EXT}:3000'
    networks:
      - app_network