version: "3.9"
networks:
  app_network:
    external: true
services:
  database:
    container_name: multicontainer_todo_database-${NODE_ENV}
    image: postgres:14-alpine
    env_file: "../../srv/src/db/.env.${NODE_ENV}"
    ports:
      - '${DATABASE_PORT_EXT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
volumes:
  postgres_data: