version: "3.9"
networks:
  app_network:
    external: true
services:
  database:
    container_name: multicontainer_todo_database-${ENVIRONMENT}
    image: postgres:14-alpine
    env_file: "./.env.${ENVIRONMENT}"
    environment:
      POSTGRES_DB:   ${POSTGRES_DB}
      POSTGRES_USER:  ${POSTGRES_USER}
      POSTGRES_PASSWORD:  ${POSTGRES_PASSWORD}
      NODE_ENV:  ${NODE_ENV}
    ports:
      - '${DATABASE_PORT_EXT}:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
volumes:
  postgres_data: